.job_template: &job_definition  # Hidden key that defines an anchor named 'job_definition'
  stage: tests
  before_script:
    - echo "deb http://deb.debian.org/debian jessie main" >> /etc/apt/sources.list
    - echo "deb-src http://deb.debian.org/debian jessie main" >> /etc/apt/sources.list
    - apt-get update -yy
    - apt-get build-dep -yy python-numpy
    - apt-get install -yy libsndfile1 libsndfile1-dev
    - pip install -e .[tests,docs]
  script:
    - py.test

stages:
  - tests

test:3.6:
  image: python:3.6
  <<: *job_definition

test:3.7:
  image: python:3.7
  <<: *job_definition

test:3.8:
  image: python:3.8
  <<: *job_definition

test:latest:
  image: python:latest
  <<: *job_definition
