language: python
cache: pip
python:
    - 3.6
    - 3.7
    - 3.8
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install python3-numpy python3-scipy
    - sudo apt-get install -qq libatlas-dev libatlas-base-dev liblapack-dev gfortran
install:
    - pip install -U pip wheel
    - pip install -e .[tests,docs]
script:
    - py.test
    - python setup.py build_sphinx
    - python setup.py egg_info -b.dev sdist --formats gztar
    - python setup.py bdist_wheel
